// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLGrWI0VxsE2xY9zubyO72QVBurIWNXfQ',
    appId: '1:39970955884:web:0b8e68eccada4412ee2e49',
    messagingSenderId: '39970955884',
    projectId: 'medicvoice-a1047',
    authDomain: 'medicvoice-a1047.firebaseapp.com',
    storageBucket: 'medicvoice-a1047.firebasestorage.app',
    measurementId: 'G-ZPXC1NWJS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJ8oMucLSyb8Bk_gXQnVM59w0qr-tmuQ',
    appId: '1:857728583965:android:f276d150d485091468b9f4',
    messagingSenderId: '857728583965',
    projectId: 'medic-d7d1c',
    storageBucket: 'medic-d7d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8k2JjB1EifuByJ61UIWqg8hZe9PGSYW4',
    appId: '1:39970955884:ios:053f2c4c03367776ee2e49',
    messagingSenderId: '39970955884',
    projectId: 'medicvoice-a1047',
    storageBucket: 'medicvoice-a1047.firebasestorage.app',
    iosBundleId: 'com.medivoice.medic',
  );
}